import { Notification } from './types';

const now = new Date();

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    type: 'delivery',
    title: 'Livraison terminée',
    message: 'Le colis LNX-2026-001 a été livré avec succès à Casablanca.',
    read: false,
    priority: 'high',
    timestamp: new Date(now.getTime() - 5 * 60 * 1000),
    actionUrl: '/tracking',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'notif-002',
    type: 'event',
    title: 'Nouvel événement planifié',
    message: 'Championnat Régional de Basketball planifié pour le 20 mai 2026.',
    read: false,
    priority: 'medium',
    timestamp: new Date(now.getTime() - 30 * 60 * 1000),
    actionUrl: '/events',
  },
  {
    id: 'notif-003',
    type: 'system',
    title: 'Mise à jour système',
    message: 'Maintenance de la plateforme prévue cette nuit à 2h00.',
    read: false,
    priority: 'low',
    timestamp: new Date(now.getTime() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'notif-004',
    type: 'delivery',
    title: 'Livraison retardée',
    message: 'Le colis LNX-2026-045 est retardé en raison des conditions de circulation.',
    read: true,
    priority: 'medium',
    timestamp: new Date(now.getTime() - 4 * 60 * 60 * 1000),
    actionUrl: '/tracking',
  },
  {
    id: 'notif-005',
    type: 'team',
    title: 'Nouveau chauffeur assigné',
    message: 'Ahmed a été assigné à la tournée #234 pour demain.',
    read: true,
    priority: 'low',
    timestamp: new Date(now.getTime() - 8 * 60 * 60 * 1000),
    actionUrl: '/drivers',
  },
  {
    id: 'notif-006',
    type: 'security',
    title: 'Alerte de sécurité',
    message: 'Nouvelle connexion détectée depuis Marrakech, Maroc.',
    read: false,
    priority: 'high',
    timestamp: new Date(now.getTime() - 12 * 60 * 60 * 1000),
  },
  {
    id: 'notif-007',
    type: 'payment',
    title: 'Paiement reçu',
    message: 'Paiement de 5 000 MAD reçu du Client #123.',
    read: true,
    priority: 'medium',
    timestamp: new Date(now.getTime() - 24 * 60 * 60 * 1000),
    actionUrl: '/payments',
  },
  {
    id: 'notif-008',
    type: 'delivery',
    title: 'Livraison confirmée',
    message: 'Le client a confirmé la réception du colis LNX-2026-089.',
    read: true,
    priority: 'low',
    timestamp: new Date(now.getTime() - 36 * 60 * 60 * 1000),
  },
  {
    id: 'notif-009',
    type: 'mention',
    title: 'Vous avez été mentionné',
    message: 'Fatima vous a mentionné dans un commentaire sur la tournée #567.',
    read: false,
    priority: 'medium',
    timestamp: new Date(now.getTime() - 48 * 60 * 60 * 1000),
    actionUrl: '/comments',
  },
  {
    id: 'notif-010',
    type: 'system',
    title: 'Sauvegarde terminée',
    message: 'Sauvegarde quotidienne effectuée avec succès.',
    read: true,
    priority: 'low',
    timestamp: new Date(now.getTime() - 72 * 60 * 60 * 1000),
  },
];

export const notificationTypeConfig: Record<string, { icon: string; color: string; bgColor: string }> = {
  delivery: { icon: 'Package', color: 'text-violet-600', bgColor: 'bg-violet-100 dark:bg-violet-900/30' },
  event: { icon: 'Calendar', color: 'text-blue-600', bgColor: 'bg-blue-100 dark:bg-blue-900/30' },
  system: { icon: 'Settings', color: 'text-muted-foreground', bgColor: 'bg-muted' },
  alert: { icon: 'AlertTriangle', color: 'text-amber-600', bgColor: 'bg-amber-100 dark:bg-amber-900/30' },
  success: { icon: 'CheckCircle', color: 'text-green-600', bgColor: 'bg-green-100 dark:bg-green-900/30' },
  error: { icon: 'XCircle', color: 'text-red-600', bgColor: 'bg-red-100 dark:bg-red-900/30' },
  warning: { icon: 'AlertTriangle', color: 'text-amber-600', bgColor: 'bg-amber-100 dark:bg-amber-900/30' },
  info: { icon: 'Info', color: 'text-blue-600', bgColor: 'bg-blue-100 dark:bg-blue-900/30' },
  mention: { icon: 'AtSign', color: 'text-violet-600', bgColor: 'bg-violet-100 dark:bg-violet-900/30' },
  payment: { icon: 'CreditCard', color: 'text-green-600', bgColor: 'bg-green-100 dark:bg-green-900/30' },
  security: { icon: 'Shield', color: 'text-amber-600', bgColor: 'bg-amber-100 dark:bg-amber-900/30' },
  team: { icon: 'Users', color: 'text-blue-600', bgColor: 'bg-blue-100 dark:bg-blue-900/30' },
};