import { Notification } from './types';

const now = new Date();

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    type: 'delivery',
    title: 'Delivery Completed',
    message: 'Package LNX-2026-001 has been successfully delivered to Casablanca.',
    read: false,
    priority: 'high',
    timestamp: new Date(now.getTime() - 5 * 60 * 1000),
    actionUrl: '/tracking',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'notif-002',
    type: 'event',
    title: 'New Event Scheduled',
    message: 'Championnat Régional de Basketball scheduled for May 20, 2026.',
    read: false,
    priority: 'medium',
    timestamp: new Date(now.getTime() - 30 * 60 * 1000),
    actionUrl: '/events',
  },
  {
    id: 'notif-003',
    type: 'system',
    title: 'System Update',
    message: 'Platform maintenance scheduled for tonight at 2:00 AM.',
    read: false,
    priority: 'low',
    timestamp: new Date(now.getTime() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'notif-004',
    type: 'delivery',
    title: 'Delivery Delayed',
    message: 'Package LNX-2026-045 is delayed due to traffic conditions.',
    read: true,
    priority: 'medium',
    timestamp: new Date(now.getTime() - 4 * 60 * 60 * 1000),
    actionUrl: '/tracking',
  },
  {
    id: 'notif-005',
    type: 'team',
    title: 'New Driver Assigned',
    message: 'Ahmed has been assigned to Route #234 for tomorrow.',
    read: true,
    priority: 'low',
    timestamp: new Date(now.getTime() - 8 * 60 * 60 * 1000),
    actionUrl: '/drivers',
  },
  {
    id: 'notif-006',
    type: 'security',
    title: 'Security Alert',
    message: 'New login detected from Marrakech, Morocco.',
    read: false,
    priority: 'high',
    timestamp: new Date(now.getTime() - 12 * 60 * 60 * 1000),
  },
  {
    id: 'notif-007',
    type: 'payment',
    title: 'Payment Received',
    message: 'Payment of MAD 5,000 received from Client #123.',
    read: true,
    priority: 'medium',
    timestamp: new Date(now.getTime() - 24 * 60 * 60 * 1000),
    actionUrl: '/payments',
  },
  {
    id: 'notif-008',
    type: 'delivery',
    title: 'Delivery Confirmed',
    message: 'Client confirmed receipt of package LNX-2026-089.',
    read: true,
    priority: 'low',
    timestamp: new Date(now.getTime() - 36 * 60 * 60 * 1000),
  },
  {
    id: 'notif-009',
    type: 'mention',
    title: 'You were mentioned',
    message: 'Fatima mentioned you in a comment about Route #567.',
    read: false,
    priority: 'medium',
    timestamp: new Date(now.getTime() - 48 * 60 * 60 * 1000),
    actionUrl: '/comments',
  },
  {
    id: 'notif-010',
    type: 'system',
    title: 'Backup Complete',
    message: 'Daily backup completed successfully.',
    read: true,
    priority: 'low',
    timestamp: new Date(now.getTime() - 72 * 60 * 60 * 1000),
  },
];

export const notificationTypeConfig: Record<string, { icon: string; color: string; bgColor: string }> = {
  delivery: { icon: 'Package', color: 'text-violet-600', bgColor: 'bg-violet-100 dark:bg-violet-900/30' },
  event: { icon: 'Calendar', color: 'text-blue-600', bgColor: 'bg-blue-100 dark:bg-blue-900/30' },
  system: { icon: 'Settings', color: 'text-muted-foreground', bgColor: 'bg-muted' },
  alert: { icon: 'AlertTriangle', color: 'text-amber-600', bgColor: 'bg-amber-100 dark:bg-amber-900/30' },
  success: { icon: 'CheckCircle', color: 'text-green-600', bgColor: 'bg-green-100 dark:bg-green-900/30' },
  error: { icon: 'XCircle', color: 'text-red-600', bgColor: 'bg-red-100 dark:bg-red-900/30' },
  warning: { icon: 'AlertTriangle', color: 'text-amber-600', bgColor: 'bg-amber-100 dark:bg-amber-900/30' },
  info: { icon: 'Info', color: 'text-blue-600', bgColor: 'bg-blue-100 dark:bg-blue-900/30' },
  mention: { icon: 'AtSign', color: 'text-violet-600', bgColor: 'bg-violet-100 dark:bg-violet-900/30' },
  payment: { icon: 'CreditCard', color: 'text-green-600', bgColor: 'bg-green-100 dark:bg-green-900/30' },
  security: { icon: 'Shield', color: 'text-amber-600', bgColor: 'bg-amber-100 dark:bg-amber-900/30' },
  team: { icon: 'Users', color: 'text-blue-600', bgColor: 'bg-blue-100 dark:bg-blue-900/30' },
};